version: '3.0'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
volumes:
  logvolume01: {}
